executors:
    controller:
      config:
        corePoolSize: 2
        maxPoolSize: 4
        keepAlive: 60
        queueCapacity: 8
    ioBlocking:
      config:
        corePoolSize: 2
        maxPoolSize: 4
        keepAlive: 60
        queue-capacity: 8
    service:
      config:
        corePoolSize: 4
        maxPoolSize: 8
        keepAlive: 1
        queueCapacity: 100




cyclone:
  processing:
    chunk-size: 1000
  data:
    hurdat2: classpath:datasets/hurdat2-1851-2024-040425.txt



logging:
  config: classpath:log4j2.xml

server:
  port: 1234


spring:
  application:
    name: florida-storms
